# Generated by Django 4.2.1 on 2023-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Demo", "0002_alter_blog_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
            ],
        ),
    ]
